### ISSUE TITLE
add it as marker

### ISSUE THREAD

**Issue by MahmoudYaser1** [topherbuckley/omnitone-PSV#1]
Hi , how are you ??
is there a way to add an audio file as marker or at least get the rotation angle of the camera at a specific location based on marker position then put the initial audio position at that point or some thing like that,  idon't know.
so what do you say sir ??

**Comment by topherbuckley** [comment]
@dekemega I had the same issue. Please find the resolution in the PSV issues [here](https://github.com/mistic100/Photo-Sphere-Viewer/issues/135):
